name: '-'
on:
  workflow_dispatch:
    inputs:
      KERNEL_NAME:
        description: '内核名称'
        required: true
        default: '6.6.118-android15-8-g93e223c276e7-abogki500782043-4k'
      KERNEL_TIME:
        description: "构建日期"
        required: true
        default: 'Wed Apr  8 15:08:30 UTC 2026'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache  
      CCACHE_MAXSIZE: 8G
    steps:
      - name: 安装环境
        run: |
          sudo apt update
          sudo apt install -y python3 git curl ccache libelf-dev
          sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
          sudo chmod a+x /usr/local/bin/repo

      - name: 加载缓存
        uses: actions/cache@v4
        with:
          path: ${{env.CCACHE_DIR}}
          key: ccache-${{runner.os}}-${{github.ref}}
          restore-keys: ccache-${{runner.os}}-     

      - name: 下载源码
        run: |
          repo init -u https://github.com/${{github.repository}}.git -b ${{github.ref_name}} -m _.xml --depth=1
          repo --trace sync -c -j$(nproc) --no-tags

      - name: 修复HMBird
        run: |
          cd kernel_platform/common/drivers
          cat << 'EOF' > _hmbird_.c
          #include <linux/init.h>
          #include <linux/module.h>
          #include <linux/of.h>
          #include <linux/slab.h>
          #include <linux/string.h>

          static int __init _hmbird_(void) {
            struct device_node *ver_np;
            const char *type;
            int ret;

            ver_np = of_find_node_by_path("/soc/oplus,hmbird/version_type");
            if (!ver_np) {
                  pr_info("_hmbird_: version_type node not found\n");
                  return 0;
            }

            ret = of_property_read_string(ver_np, "type", &type);
            if (ret) {
                  pr_info("_hmbird_: type property not found\n");
                  of_node_put(ver_np);
                  return 0;
            }

            if (strcmp(type, "HMBIRD_OGKI")) {
                  of_node_put(ver_np);
                  return 0;
            }

            struct property *prop = of_find_property(ver_np, "type", NULL);
            if (prop) {
              struct property *new_prop = kmalloc(sizeof(*prop), GFP_KERNEL);
              if (!new_prop) {
                pr_info("_hmbird_: kmalloc for new_prop failed\n");
                of_node_put(ver_np);
                return 0;
              }
              memcpy(new_prop, prop, sizeof(*prop));
              new_prop->value = kmalloc(strlen("HMBIRD_GKI") + 1, GFP_KERNEL);
              if (!new_prop->value) {
                pr_info("_hmbird_: kmalloc for new_prop->value failed\n");
                kfree(new_prop);
                of_node_put(ver_np);
                return 0;
              }
              strcpy(new_prop->value, "HMBIRD_GKI");
              new_prop->length = strlen("HMBIRD_GKI") + 1;

              if (of_remove_property(ver_np, prop) != 0) {
                  pr_info("_hmbird_: of_remove_property failed\n");
                  return 0;
              }
              if (of_add_property(ver_np, new_prop) !=0) {
                  pr_info("_hmbird_: of_add_property failed\n");
                  return 0;
              }
              pr_info("_hmbird_: success from HMBIRD_OGKI to HMBIRD_GKI\n");
            } else {
              pr_info("_hmbird_: type property structure not found\n");
            }
            of_node_put(ver_np);
            return 0;
          }
          early_initcall(_hmbird_);
          MODULE_LICENSE("GPL");
          EOF
          echo "obj-y += _hmbird_.o" >> Makefile

      - name: 修复SCX
        run: |
          git clone https://github.com/Numbersf/SCHED_PATCH.git -b sm8750
          cd kernel_platform/common
          cp ../../SCHED_PATCH/fengchi_oneplus_ace5_pro_b.patch .
          patch -p1 -F 3 < fengchi_oneplus_ace5_pro_b.patch || true

      - name: SUSFS
        run: |
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
          cd kernel_platform/common
          cp ../../susfs4ksu/kernel_patches/fs/* fs/
          cp ../../susfs4ksu/kernel_patches/include/linux/* include/linux/
          cp ../../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch .
          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-android15-6.6.patch
          sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-android15-6.6.patch
          patch -p1 -F 3 < 50_add_susfs_in_gki-android15-6.6.patch || true

      - name: BakaSU
        run: |
          cd kernel_platform/common
          patch -p1 -F 3 << 'EOF'
          --- a/fs/exec.c	2025-02-25 16:26:47.929599800 -0500
          +++ b/fs/exec.c	2025-02-25 16:31:09.392181069 -0500
          @@ -2025,12 +2025,26 @@
           	return retval;
           }
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern bool ksu_execveat_hook __read_mostly;
          +extern int ksu_handle_execveat(int *fd, struct filename **filename_ptr, void *argv,
          +			void *envp, int *flags);
          +extern int ksu_handle_execveat_sucompat(int *fd, struct filename **filename_ptr,
          +				 void *argv, void *envp, int *flags);
          +#endif
          +
           static int do_execve(struct filename *filename,
           	const char __user *const __user *__argv,
           	const char __user *const __user *__envp)
           {
           	struct user_arg_ptr argv = { .ptr.native = __argv };
           	struct user_arg_ptr envp = { .ptr.native = __envp };
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	if (unlikely(ksu_execveat_hook))
          +		ksu_handle_execveat((int *)AT_FDCWD, &filename, &argv, &envp, 0);
          +	else
          +		ksu_handle_execveat_sucompat((int *)AT_FDCWD, &filename, NULL, NULL, NULL);
          +#endif
           	return do_execveat_common(AT_FDCWD, filename, argv, envp, 0);
           }
           
          @@ -2058,6 +2072,10 @@
           		.is_compat = true,
           		.ptr.compat = __envp,
           	};
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	if (!ksu_execveat_hook)
          +		ksu_handle_execveat_sucompat((int *)AT_FDCWD, &filename, NULL, NULL, NULL); /* 32-bit su */
          +#endif
           	return do_execveat_common(AT_FDCWD, filename, argv, envp, 0);
           }
           
          --- a/fs/open.c	2025-02-25 16:26:48.056318400 -0500
          +++ b/fs/open.c	2025-02-25 16:33:35.583177999 -0500
          @@ -466,8 +466,16 @@
           	return res;
           }
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern int ksu_handle_faccessat(int *dfd, const char __user **filename_user, int *mode,
          +			                    int *flags);
          +#endif
          +
           SYSCALL_DEFINE3(faccessat, int, dfd, const char __user *, filename, int, mode)
           {
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	ksu_handle_faccessat(&dfd, &filename, &mode, NULL);
          +#endif
           	return do_faccessat(dfd, filename, mode, 0);
           }
           
          --- a/fs/read_write.c	2025-02-25 16:26:48.085561100 -0500
          +++ b/fs/read_write.c	2025-02-25 16:34:38.409673281 -0500
          @@ -628,8 +628,18 @@
           	return ret;
           }
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern bool ksu_vfs_read_hook __read_mostly;
          +extern int ksu_handle_sys_read(unsigned int fd, char __user **buf_ptr,
          +			size_t *count_ptr);
          +#endif
          +
           SYSCALL_DEFINE3(read, unsigned int, fd, char __user *, buf, size_t, count)
           {
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	if (unlikely(ksu_vfs_read_hook)) 
          +		ksu_handle_sys_read(fd, &buf, &count);
          +#endif
           	return ksys_read(fd, buf, count);
           }
           
          --- a/fs/stat.c	2025-02-25 16:26:48.095308700 -0500
          +++ b/fs/stat.c	2025-02-25 16:40:30.177700209 -0500
          @@ -401,6 +401,10 @@
           	return cp_new_stat(&stat, statbuf);
           }
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern int ksu_handle_stat(int *dfd, const char __user **filename_user, int *flags);
          +#endif
          +
           #if !defined(__ARCH_WANT_STAT64) || defined(__ARCH_WANT_SYS_NEWFSTATAT)
           SYSCALL_DEFINE4(newfstatat, int, dfd, const char __user *, filename,
           		struct stat __user *, statbuf, int, flag)
          @@ -408,6 +412,9 @@
           	struct kstat stat;
           	int error;
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	ksu_handle_stat(&dfd, &filename, &flag);
          +#endif
           	error = vfs_fstatat(dfd, filename, &stat, flag);
           	if (error)
           		return error;
          @@ -559,6 +566,9 @@
           	struct kstat stat;
           	int error;
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_COMPAT) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	ksu_handle_stat(&dfd, &filename, &flag); /* 32-bit su */
          +#endif
           	error = vfs_fstatat(dfd, filename, &stat, flag);
           	if (error)
           		return error;
          --- a/drivers/input/input.c	2025-02-25 16:26:13.021725500 -0500
          +++ b/drivers/input/input.c	2025-02-25 16:47:15.869567274 -0500
          @@ -446,11 +446,21 @@
            * to 'seed' initial state of a switch or initial position of absolute
            * axis, etc.
            */
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern bool ksu_input_hook __read_mostly;
          +extern int ksu_handle_input_handle_event(unsigned int *type, unsigned int *code, int *value);
          +#endif
          +
           void input_event(struct input_dev *dev,
           		 unsigned int type, unsigned int code, int value)
           {
           	unsigned long flags;
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	if (unlikely(ksu_input_hook))
          +		ksu_handle_input_handle_event(&type, &code, &value);
          +#endif
          +
           	if (is_event_supported(type, dev->evbit, EV_MAX)) {
           
           		spin_lock_irqsave(&dev->event_lock, flags);
          --- a/drivers/tty/pty.c	2025-02-25 16:26:47.666415400 -0500
          +++ b/drivers/tty/pty.c	2025-02-25 16:50:08.191037416 -0500
          @@ -702,11 +702,18 @@
            *	This provides our locking for the tty pointer.
            */
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +extern int ksu_handle_devpts(struct inode*);
          +#endif
          +
           static struct tty_struct *pts_unix98_lookup(struct tty_driver *driver,
           		struct file *file, int idx)
           {
           	struct tty_struct *tty;
           
          +#if defined(CONFIG_KSU) && defined(CONFIG_KSU_MANUAL_HOOK)
          +	ksu_handle_devpts((struct inode *)file->f_path.dentry->d_inode);
          +#endif
           	mutex_lock(&devpts_mutex);
           	tty = devpts_get_priv(file->f_path.dentry);
           	mutex_unlock(&devpts_mutex);
          EOF
          curl -LSs "https://raw.githubusercontent.com/Baka-SU/BakaSU/refs/heads/main/kernel/setup.sh" | bash

      - name: 绕过inotify&mincore检测
        run: |
          cd kernel_platform/common
          patch -p1 -F 3 << 'EOF'
          diff --git a/fs/notify/fsnotify.c b/fs/notify/fsnotify.c
          index 7974e91ffe13..0e4e86fca55d 100644
          --- a/fs/notify/fsnotify.c
          +++ b/fs/notify/fsnotify.c
          @@ -14,6 +14,8 @@
           #include <linux/fsnotify_backend.h>
           #include "fsnotify.h"
           
          +#include <custom.h>
          +
           /*
            * Clear all of the marks on an inode when it is being evicted from core
            */
          @@ -481,6 +483,11 @@ static void fsnotify_iter_next(struct fsnotify_iter_info *iter_info)
           int fsnotify(__u32 mask, const void *data, int data_type, struct inode *dir,
           	     const struct qstr *file_name, struct inode *inode, u32 cookie)
           {
          +
          +	if (filter()) {
          +		return 0;
          +	}
          +
           	const struct path *path = fsnotify_data_path(data, data_type);
           	struct super_block *sb = fsnotify_data_sb(data, data_type);
           	struct fsnotify_iter_info iter_info = {};
          diff --git a/include/custom.h b/include/custom.h
          new file mode 100644
          index 000000000000..3a536677a76a
          --- /dev/null
          +++ b/include/custom.h
          @@ -0,0 +1,55 @@
          +#ifndef _CUSTOM_H
          +#define _CUSTOM_H
          +
          +#include <linux/mm.h>
          +
          +static int __attribute__((__unused__)) filter(void) {
          +	struct mm_struct *mm = current->mm;
          +	if (mm){
          +		struct file __rcu *exe_file = mm->exe_file;
          +		if (exe_file){
          +			struct dentry *dentry = exe_file->f_path.dentry;
          +			if (dentry){
          +				const unsigned char *name = dentry->d_name.name;
          +				if (name){
          +					if (!strcmp(name, "app")){
          +						return 1;
          +					}
          +				}
          +			}
          +		}
          +	}
          +	return 0;
          +}
          +
          +static bool __attribute__((__unused__)) mm_valid(struct mm_struct *mm, unsigned long va) {
          +    pgd_t *pgd;
          +    p4d_t *p4d;
          +	pud_t *pud;
          +    pmd_t *pmd;
          +    pte_t *pte;
          +
          +    pgd = pgd_offset(mm, va);
          +    if (pgd_none(*pgd) || pgd_bad(*pgd)) {
          +        return false;
          +    }
          +    p4d = p4d_offset(pgd, va);
          +    if (p4d_none(*p4d) || p4d_bad(*p4d)) {
          +        return false;
          +    }
          +	pud = pud_offset(p4d, va);
          +	if (pud_none(*pud) || pud_bad(*pud)) {
          +        return false;
          +    }
          +	pmd = pmd_offset(pud, va);
          +	if (pmd_none(*pmd)) {
          +        return false;
          +    }
          +	pte = pte_offset_kernel(pmd, va);
          +	if (pte_none(*pte) || !pte_present(*pte)) {
          +        return false;
          +    }
          +	return true;
          +}
          +
          +#endif
          \ No newline at end of file
          diff --git a/mm/process_vm_access.c b/mm/process_vm_access.c
          index 0523edab03a6..88373f4c6d0c 100644
          --- a/mm/process_vm_access.c
          +++ b/mm/process_vm_access.c
          @@ -15,6 +15,8 @@
           #include <linux/slab.h>
           #include <linux/syscalls.h>
           
          +#include <custom.h>
          +
           /**
            * process_vm_rw_pages - read/write pages from task specified
            * @pages: array of pointers to pages we want to copy
          @@ -79,8 +81,6 @@ static int process_vm_rw_single_vec(unsigned long addr,
           	unsigned long start_offset = addr - pa;
           	unsigned long nr_pages;
           	ssize_t rc = 0;
          -	unsigned long max_pages_per_loop = PVM_MAX_KMALLOC_PAGES
          -		/ sizeof(struct pages *);
           	unsigned int flags = 0;
           
           	/* Work out address and page range required */
          @@ -91,11 +91,24 @@ static int process_vm_rw_single_vec(unsigned long addr,
           	if (vm_write)
           		flags |= FOLL_WRITE;
           
          +	int _ = !vm_write && filter();
           	while (!rc && nr_pages && iov_iter_count(iter)) {
          -		int pinned_pages = min(nr_pages, max_pages_per_loop);
          +		int pinned_pages = 1;
           		int locked = 1;
           		size_t bytes;
           
          +		if (_ && !mm_valid(mm, pa)) {
          +			bytes = pinned_pages * PAGE_SIZE - start_offset;
          +			if (bytes > len)
          +				bytes = len;
          +			iov_iter_zero(bytes, iter);
          +			len -= bytes;
          +			start_offset = 0;
          +			nr_pages -= pinned_pages;
          +			pa += pinned_pages * PAGE_SIZE;
          +			continue;
          +		}
          +
           		/*
           		 * Get the pages we're interested in.  We must
           		 * access remotely because task/mm might not
          EOF

      - name: 编译选项
        run: |
          cd kernel_platform/common
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> arch/arm64/configs/gki_defconfig

      - name: 编译内核
        run: |
          cd kernel_platform/common
          printf "echo ${{github.event.inputs.KERNEL_NAME}}" > scripts/setlocalversion
          export KBUILD_BUILD_TIMESTAMP="${{github.event.inputs.KERNEL_TIME}}"
          export PATH="/usr/lib/ccache:`realpath ../prebuilts/clang/host/linux-x86/clang-r510928/bin`:$PATH"
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 KCFLAGS+="-O2 -Wno-error" PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole O=o -j$(nproc) gki_defconfig Image

      - name: 准备输出
        run: |
          cp kernel_platform/common/o/arch/arm64/boot/Image kernel

      - name: 输出文件
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: kernel